import type { Question } from '../types.js';

// Hand-curated questions from source.md with exact provenance
const curatedQuestions: Question[] = [
  // Section 1: Domestic and Behavioral "Average" (2026 Data)
  {
    id: 'curated-001',
    question: 'According to a February 2026 survey, what color is the most popular for marking BINGO cards?',
    correct_answer: 'Purple',
    incorrect_answers: [],
    type: 'free_response',
    category: 'General Knowledge',
    difficulty: 'medium',
    tags: ['behavioral', 'survey', '2026'],
    source: {
      name: 'Question Impossible Archive | 93.3 The Drive',
      url: 'https://www.933thedrive.com/question-impossible-archive/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-002',
    question: '40% of people surveyed in early 2026 admitted they did NOT do this activity at all during the year 2025. What is it?',
    correct_answer: 'Read a book',
    incorrect_answers: [],
    type: 'free_response',
    category: 'General Knowledge',
    difficulty: 'medium',
    tags: ['behavioral', 'survey', '2026'],
    source: {
      name: 'Question Impossible Archive | 93.3 The Drive',
      url: 'https://www.933thedrive.com/question-impossible-archive/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-003',
    question: 'About 26 million American employees reportedly plan to do this specific thing on the Monday following the Super Bowl in February 2026. What is it?',
    correct_answer: 'Miss work',
    incorrect_answers: [],
    type: 'free_response',
    category: 'General Knowledge',
    difficulty: 'easy',
    tags: ['behavioral', 'super-bowl', '2026'],
    source: {
      name: 'Question Impossible Archive | 93.3 The Drive',
      url: 'https://www.933thedrive.com/question-impossible-archive/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-004',
    question: 'Redheads, according to a 2026 survey, are more likely than any other hair color group to do what specific activity while in their car?',
    correct_answer: 'Sing',
    incorrect_answers: [],
    type: 'free_response',
    category: 'General Knowledge',
    difficulty: 'hard',
    tags: ['behavioral', 'survey', '2026'],
    source: {
      name: 'Question Impossible Archive | 93.3 The Drive',
      url: 'https://www.933thedrive.com/question-impossible-archive/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-005',
    question: 'Each year, approximately 9,000 Americans are admitted to the Emergency Room for injuries involving what common bathroom item?',
    correct_answer: 'A toothbrush',
    incorrect_answers: [],
    type: 'free_response',
    category: 'General Knowledge',
    difficulty: 'hard',
    tags: ['behavioral', 'statistics'],
    source: {
      name: 'Question Impossible Archive | 93.3 The Drive',
      url: 'https://www.933thedrive.com/question-impossible-archive/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-006',
    question: 'How many remote controls does the average household own, according to a February 2026 survey?',
    correct_answer: 'Four',
    incorrect_answers: [],
    type: 'free_response',
    category: 'General Knowledge',
    difficulty: 'medium',
    tags: ['behavioral', 'survey', '2026'],
    source: {
      name: 'Question Impossible Archive | 93.3 The Drive',
      url: 'https://www.933thedrive.com/question-impossible-archive/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-007',
    question: 'What is the estimated value of loose change held collectively by Americans?',
    correct_answer: '$15 Billion',
    incorrect_answers: [],
    type: 'free_response',
    category: 'General Knowledge',
    difficulty: 'hard',
    tags: ['behavioral', 'statistics', '2026'],
    source: {
      name: 'Question Impossible Archive | 93.3 The Drive',
      url: 'https://www.933thedrive.com/question-impossible-archive/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-008',
    question: 'What is the average number of pets an individual will own in their lifetime?',
    correct_answer: '24',
    incorrect_answers: [],
    type: 'free_response',
    category: 'General Knowledge',
    difficulty: 'hard',
    tags: ['behavioral', 'statistics', '2026'],
    source: {
      name: 'Question Impossible Archive | 93.3 The Drive',
      url: 'https://www.933thedrive.com/question-impossible-archive/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },

  // Section 2: Scouting and Historical Traditions
  {
    id: 'curated-009',
    question: 'Juliette Gordon Low founded the Girl Scouts in 1912. What was the name of the organization\'s first official handbook?',
    correct_answer: 'How Girls Can Help Their Country',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Scouting',
    difficulty: 'hard',
    tags: ['scouting', 'history', 'girl-scouts'],
    source: {
      name: 'Girl Scouts of Virginia Skyline Council Archives',
      url: 'https://www.gsvsc.org/content/dam/gsvsc-redesign/pdfs_docs/Archives/Archives%20Group%20History%20Quiz.doc',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-010',
    question: 'Who is credited as the founder of the global Scouting movement after organizing the 1907 Brownsea Island camp?',
    correct_answer: 'Robert Baden-Powell',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Scouting',
    difficulty: 'easy',
    tags: ['scouting', 'history', 'founders'],
    source: {
      name: 'Education Quizzes - Scout Quiz',
      url: 'https://www.educationquizzes.com/specialist/scouts-uk/scout-quiz-scouting-through-the-ages/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-011',
    question: 'What is the Scout Motto, originally coined by Baden-Powell?',
    correct_answer: 'Be Prepared',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Scouting',
    difficulty: 'easy',
    tags: ['scouting', 'motto'],
    source: {
      name: 'Golden Spread Council - Scout Trivia',
      url: 'https://goldenspread.org/wp-content/uploads/2017/06/Scout-trivia-questions-and-answers.pdf',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-012',
    question: 'What do the two stars on the Scouting badge represent?',
    correct_answer: 'Truth and Knowledge',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Scouting',
    difficulty: 'medium',
    tags: ['scouting', 'symbology'],
    source: {
      name: 'Golden Spread Council - Scout Trivia',
      url: 'https://goldenspread.org/wp-content/uploads/2017/06/Scout-trivia-questions-and-answers.pdf',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-013',
    question: 'Who founded the Girl Guides in 1910?',
    correct_answer: 'Agnes Baden-Powell',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Scouting',
    difficulty: 'medium',
    tags: ['scouting', 'history', 'girl-guides'],
    source: {
      name: 'Scouting History Quiz - GSCouts',
      url: 'https://gscouts.org.uk/wp-content/uploads/2020/04/Scouting-Quiz.pdf',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-014',
    question: 'Which country hosted the first World Scout Jamboree in 1920?',
    correct_answer: 'United Kingdom',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Scouting',
    difficulty: 'medium',
    tags: ['scouting', 'history', 'jamboree'],
    source: {
      name: 'Education Quizzes - Scout Quiz',
      url: 'https://www.educationquizzes.com/specialist/scouts-uk/scout-quiz-scouting-through-the-ages/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-015',
    question: 'In 1963, the highest award a Girl Scout could earn was changed from the "Curved Bar" to what name?',
    correct_answer: 'First Class',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Scouting',
    difficulty: 'hard',
    tags: ['scouting', 'history', 'girl-scouts', 'awards'],
    source: {
      name: 'Girl Scouts of Virginia Skyline Council Archives',
      url: 'https://www.gsvsc.org/content/dam/gsvsc-redesign/pdfs_docs/Archives/Archives%20Group%20History%20Quiz.doc',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },

  // Section 3: Nostalgia and Cultural Legacy (80s/90s)
  {
    id: 'curated-016',
    question: 'What was the name of the high school attended by the characters in the 1990s sitcom "Saved by the Bell"?',
    correct_answer: 'Bayside High',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Entertainment',
    difficulty: 'easy',
    tags: ['90s', 'television', 'nostalgia'],
    source: {
      name: '90s Trivia Questions & Answers - Parade',
      url: 'https://parade.com/1075273/jessicasager/90s-trivia/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-017',
    question: 'In 1984, which female athlete became the first woman to run on a major party\'s presidential ticket in the United States?',
    correct_answer: 'Geraldine Ferraro',
    incorrect_answers: [],
    type: 'free_response',
    category: 'History',
    difficulty: 'medium',
    tags: ['80s', 'politics', 'women'],
    source: {
      name: '80s Trivia: 200+ Pop Culture Questions',
      url: 'https://rerunthe80s.com/blogs/news/80s-trivia-questions',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-018',
    question: 'Whitney Houston\'s massive 1992 hit "I Will Always Love You" was originally written and performed by which country music legend?',
    correct_answer: 'Dolly Parton',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Music',
    difficulty: 'easy',
    tags: ['90s', 'music', 'nostalgia'],
    source: {
      name: '90s Trivia Questions & Answers - Parade',
      url: 'https://parade.com/1075273/jessicasager/90s-trivia/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-019',
    question: 'What was the name of the hotel in the 1980 film "The Shining," based on Stephen King\'s novel?',
    correct_answer: 'The Overlook Hotel',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Entertainment',
    difficulty: 'easy',
    tags: ['80s', 'movies', 'horror'],
    source: {
      name: '80s Trivia: 200+ Pop Culture Questions',
      url: 'https://rerunthe80s.com/blogs/news/80s-trivia-questions',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-020',
    question: 'Which boy band released the global hit "I Want It That Way" in 1999?',
    correct_answer: 'Backstreet Boys',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Music',
    difficulty: 'easy',
    tags: ['90s', 'music', 'boy-bands'],
    source: {
      name: '90s Trivia Questions & Answers - Parade',
      url: 'https://parade.com/1075273/jessicasager/90s-trivia/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },

  // Section 4: Science, Nature, and the Modern World
  {
    id: 'curated-021',
    question: 'On January 25, 2026, Alex Honnold completed a free solo climb of Taipei 101. In which country is this building located?',
    correct_answer: 'Taiwan',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Geography',
    difficulty: 'easy',
    tags: ['2026', 'sports', 'climbing'],
    source: {
      name: 'Sporcle Events - Corner Brewery Trivia Recap',
      url: 'https://hebontheweb.blog/2026/02/12/trivia-recap-game-884-february-11-2026-sporcle-events-corner-brewery-ypsilanti-mi/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-022',
    question: 'What 1940 Ernest Hemingway novel shares its title with a 1984 song by the heavy metal band Metallica?',
    correct_answer: 'For Whom the Bell Tolls',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Arts & Literature',
    difficulty: 'medium',
    tags: ['literature', 'music', 'metallica', 'hemingway'],
    source: {
      name: 'HebSpeaks Trivia Recap',
      url: 'https://hebontheweb.blog/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-023',
    question: 'In early 2026, Rhode Island announced it might stop featuring what iconic Hasbro character on its specialty license plates?',
    correct_answer: 'Mr. Potato Head',
    incorrect_answers: [],
    type: 'free_response',
    category: 'General Knowledge',
    difficulty: 'medium',
    tags: ['2026', 'news', 'toys'],
    source: {
      name: 'Sporcle Events - Corner Brewery Trivia Recap',
      url: 'https://hebontheweb.blog/2026/02/12/trivia-recap-game-884-february-11-2026-sporcle-events-corner-brewery-ypsilanti-mi/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-024',
    question: 'Which social media founder\'s first-ever tweet was sold as an NFT for $2.9 million in 2021?',
    correct_answer: 'Jack Dorsey',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Science & Technology',
    difficulty: 'medium',
    tags: ['technology', 'social-media', 'nft'],
    source: {
      name: 'HebSpeaks Trivia Recap',
      url: 'https://hebontheweb.blog/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-025',
    question: 'Ridley Scott\'s famous 1984 Super Bowl commercial introduced which product?',
    correct_answer: 'The Apple Macintosh',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Entertainment',
    difficulty: 'medium',
    tags: ['80s', 'technology', 'advertising'],
    source: {
      name: 'HebSpeaks Trivia Plans',
      url: 'https://hebontheweb.blog/2026/02/08/trivia-plans-week-of-february-8-2026/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-026',
    question: 'What character did Bruce Willis play in "Pulp Fiction"?',
    correct_answer: 'Butch Coolidge',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Entertainment',
    difficulty: 'medium',
    tags: ['90s', 'movies', 'tarantino'],
    source: {
      name: 'HebSpeaks Trivia Plans',
      url: 'https://hebontheweb.blog/2026/02/08/trivia-plans-week-of-february-8-2026/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-027',
    question: 'What was the first animated film to be nominated for the Best Picture Oscar?',
    correct_answer: 'Beauty and the Beast',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Entertainment',
    difficulty: 'medium',
    tags: ['90s', 'movies', 'animation', 'oscars'],
    source: {
      name: 'HebSpeaks Trivia Plans',
      url: 'https://hebontheweb.blog/2026/02/08/trivia-plans-week-of-february-8-2026/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-028',
    question: 'What percentage of airline passengers admit to "mid-flight flirting," according to a February 2026 survey?',
    correct_answer: '45%',
    incorrect_answers: [],
    type: 'free_response',
    category: 'General Knowledge',
    difficulty: 'hard',
    tags: ['behavioral', 'survey', '2026'],
    source: {
      name: 'Question Impossible Archive | 93.3 The Drive',
      url: 'https://www.933thedrive.com/question-impossible-archive/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-029',
    question: 'According to surveys, where do most Olympians keep their medals?',
    correct_answer: 'Sock drawer',
    incorrect_answers: [],
    type: 'free_response',
    category: 'Sports',
    difficulty: 'hard',
    tags: ['behavioral', 'sports', 'olympics'],
    source: {
      name: 'Question Impossible Archive | 93.3 The Drive',
      url: 'https://www.933thedrive.com/question-impossible-archive/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
  {
    id: 'curated-030',
    question: 'How many times will the average person shake hands in a lifetime?',
    correct_answer: '15,000',
    incorrect_answers: [],
    type: 'free_response',
    category: 'General Knowledge',
    difficulty: 'hard',
    tags: ['behavioral', 'statistics'],
    source: {
      name: 'Question Impossible Archive | 93.3 The Drive',
      url: 'https://www.933thedrive.com/question-impossible-archive/',
      date_sourced: '2026-03-02',
      license: 'Fair use',
    },
  },
];

export function getCuratedQuestions(): Question[] {
  return curatedQuestions;
}
